spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: ${USER_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/users/**
            - id: booking-service
              uri: ${BOOKING_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/bookings/**
            - id: tour-service
              uri: ${TOUR_SERVICE_URL:http://localhost:8084}
              predicates:
                - Path=/api/tours/**
            - id: customer-service
              uri: ${CUSTOMER_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/customers/**
            - id: partner-service
              uri: ${PARTNER_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/api/partners/**
server:
  port: 8080
