spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: partner-service
              uri: http://partner-service:8085
              predicates:
                - Path=/api/partners/**
            - id: tour-service
              uri: http://tour-service:8084
              predicates:
                - Path=/api/tours/**
            - id: customer-service
              uri: http://customer-service:8082
              predicates:
                - Path=/api/customers/**
            - id: booking-service
              uri: http://booking-service:8083
              predicates:
                - Path=/api/bookings/**
            - id: user-service
              uri: http://user-service:8081
              predicates:
                - Path=/api/users/**
server:
  port: 8080
