# ---------------- DATABASE USER ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-user-db
  namespace: travel-booking-system
spec:
  selector:
    matchLabels:
      db: mysql-user
  template:
    metadata:
      labels:
        db: mysql-user
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "pbhyclls"
            - name: MYSQL_DATABASE
              value: "user_db"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-user-db
  namespace: travel-booking-system
spec:
  selector:
    db: mysql-user
  ports:
    - port: 3306
---
# ---------------- DATABASE CUSTOMER ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-customer-db
  namespace: travel-booking-system
spec:
  selector:
    matchLabels:
      db: mysql-customer
  template:
    metadata:
      labels:
        db: mysql-customer
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "pbhyclls"
            - name: MYSQL_DATABASE
              value: "customer_db"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-customer-db
  namespace: travel-booking-system
spec:
  selector:
    db: mysql-customer
  ports:
    - port: 3306
---
# ---------------- DATABASE TOUR ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-tour-db
  namespace: travel-booking-system
spec:
  selector:
    matchLabels:
      db: mysql-tour
  template:
    metadata:
      labels:
        db: mysql-tour
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "pbhyclls"
            - name: MYSQL_DATABASE
              value: "tour_db"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-tour-db
  namespace: travel-booking-system
spec:
  selector:
    db: mysql-tour
  ports:
    - port: 3306
---
# ---------------- DATABASE BOOKING ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-booking-db
  namespace: travel-booking-system
spec:
  selector:
    matchLabels:
      db: mysql-booking
  template:
    metadata:
      labels:
        db: mysql-booking
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "pbhyclls"
            - name: MYSQL_DATABASE
              value: "booking_db"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-booking-db
  namespace: travel-booking-system
spec:
  selector:
    db: mysql-booking
  ports:
    - port: 3306
---
# ---------------- DATABASE PARTNER ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-partner-db
  namespace: travel-booking-system
spec:
  selector:
    matchLabels:
      db: mysql-partner
  template:
    metadata:
      labels:
        db: mysql-partner
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "pbhyclls"
            - name: MYSQL_DATABASE
              value: "partner_db"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-partner-db
  namespace: travel-booking-system
spec:
  selector:
    db: mysql-partner
  ports:
    - port: 3306