apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: travel-booking-system
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "pbhyclls"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  namespace: travel-booking-system
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS user_db;
    CREATE DATABASE IF NOT EXISTS customer_db;
    CREATE DATABASE IF NOT EXISTS tour_db;
    CREATE DATABASE IF NOT EXISTS booking_db;
    CREATE DATABASE IF NOT EXISTS partner_db;
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: travel-booking-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: travel-booking-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: init-sql
          configMap:
            name: db-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  namespace: travel-booking-system
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306